buildscript {
    ext.kotlin_version = '1.9.22'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

// THE FIX: Mock the 'flutter' object that geolocator expects
ext {
    flutter = [
        compileSdkVersion: 34,
        minSdkVersion: 21,
        targetSdkVersion: 34,
        versionCode: 1,
        versionName: '1.0.0'
    ]
    
    // Also keep flat versions just in case
    compileSdkVersion = 34
    minSdkVersion = 21
    targetSdkVersion = 34
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
